apiVersion: v1
kind: Service
metadata:
  name: leaflet-enotary-ui-service
spec:
  type: NodePort
  selector:
    app: leaflet-enotary-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
